### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by kennyk65** [lucioveloso/cli2cloudformation#2]
Thanks for putting this feature together!

I'm getting an error when I try to run it: "No JSON object could be decoded".  I'm afraid that is the only info that makes it to CloudWatch Logs.  I made a pretty simple template to illustrate the problem:  https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/my-custom-resource-demo.template.yml

Any thoughts?

**Comment by kennyk65** [comment]
I tried executing your Lambda function directly via a Lambda test event:

```
{
  "StackId": "arn:aws:cloudformation:us-west-2:EXAMPLE/stack-name/guid",
  "ResponseURL": "http://pre-signed-S3-url-for-response",
  "ResourceProperties": {
    "StackName": "stack-name",
    "CliCommandCreate": "s3 cp s3://kk-site s3://custom-resource-demonstration --recursive",
    "List": [
      "1",
      "2",
      "3"
    ]
  },
  "RequestType": "Create",
  "ResourceType": "Custom::TestResource",
  "RequestId": "unique id for this create request",
  "LogicalResourceId": "MyTestResource"
}
```


It produced this output:

```
START RequestId: f36aa04d-f03a-11e7-8601-c15978dae992 Version: $LATEST
No JSON object could be decoded
Log Reason: Failed to execute the command.
HTTPConnectionPool(host='pre-signed-s3-url-for-response', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76a0e8ac90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='pre-signed-s3-url-for-response', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76a0e8ac90>: Failed to establish a new connection: [Errno -2] Name or service not known',)): ConnectionError
Traceback (most recent call last):
  File "/var/task/index.py", line 38, in lambda_handler
    sendResponseCfn(event, context, "FAILED", null_return, "Failed to execute the command.")
  File "/var/task/index.py", line 62, in sendResponseCfn
    requests.put(event['ResponseURL'], data=json.dumps(response_body))
  File "/var/task/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/var/task/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/task/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='pre-signed-s3-url-for-response', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f76a0e8ac90>: Failed to establish a new connection: [Errno -2] Name or service not known',))

END RequestId: f36aa04d-f03a-11e7-8601-c15978dae992
REPORT RequestId: f36aa04d-f03a-11e7-8601-c15978dae992	Duration: 2010.12 ms	Billed Duration: 2100 ms 	Memory Size: 256 MB	Max Memory Used: 51 MB	

```
It seems as if the command I'm executing (and variations of it) do not return JSON, therefore are not considered a successful execution.  The rest of it is just blowing up on that signed URL after the fact.

**Comment by lucioveloso** [comment]
Hi,

This error appears due the ResponseURL in your event is invalid - http://pre-signed-S3-url-for-response (that does not exist). Am I wrong?

Btw, sorry for delaying answer. I just noticed it now =/. Are you still suffering this issue?

**Comment by lucioveloso** [comment]
Hi,

I gonna close this issue due inactivity. If you persist facing this issue, just let me know.

**Comment by kennyk65** [comment]
Hi Lucio,

The 'pre-signed-S3-url-for-response' is an obfuscation for an actual URL.  I would not post a live presigned URL on a public forum.

Have you ever gotten this to work?

thanks,
k
